use anyhow::{Context, Result, bail};
use arcantry_core::catalog;
use serde_json::json;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_NOTICE: &str = "Generated by xtask. Do not edit directly.";

struct Section<'a> {
  title: &'a str,
  skills: Vec<&'a catalog::CatalogEntry>,
}

pub fn run(root: &Path, check: bool, docs_only: bool) -> Result<()> {
  let root = root
    .canonicalize()
    .with_context(|| format!("Could not resolve generation root {}.", root.display()))?;
  let generated_docs_root = root.join("apps/docs/src/content/docs/_generated");
  let details_root = generated_docs_root.join("skills");
  let generated_source_root = root.join("apps/docs/src/generated");
  let generated_public_root = root.join("apps/docs/public/schemas");

  if !check {
    remove_generated(&generated_docs_root)?;
    remove_generated(&generated_source_root)?;
    remove_generated(&generated_public_root)?;
  }

  let mut stale = false;
  project(
    &generated_public_root.join("arcantry-config-v1.tosd"),
    &fs::read_to_string(root.join("schemas/arcantry-config-v1.tosd"))?,
    false,
    check,
    &mut stale,
  )?;

  let (valid, errors, catalog) = catalog::validate(&root);
  if !valid {
    bail!("{}", errors.join("\n"));
  }
  let catalog = catalog.context("Catalog validation returned no catalog.")?;
  let version = arcantry_core::release::latest_standard_release_version(&root)?;

  if !docs_only {
    project_plugins(&root, &version, check, &mut stale)?;
  }

  let sections = [
    ("self-improvement", "Self improvement"),
    ("repo-safely", "Repo safely"),
    ("content-safely", "Content safely"),
  ]
  .into_iter()
  .map(|(family, title)| Section {
    title,
    skills: catalog
      .skills
      .iter()
      .filter(|entry| entry.family == family)
      .collect(),
  })
  .collect::<Vec<_>>();

  let mut cards = BTreeMap::new();
  let mut display_names = BTreeMap::new();
  for entry in &catalog.skills {
    let metadata = catalog::load_skill_metadata(&root, &entry.name)?;
    let (_, description) = catalog::load_skill_frontmatter(&root, &entry.name)?;
    let agent = catalog::load_skill_agent(&root, &entry.name)?;
    display_names.insert(entry.name.clone(), agent.display_name.clone());
    cards.insert(
      entry.name.clone(),
      format!(
        "<a class=\"skill-catalog-card\" href=\"/skills/{}/\">\n  <p class=\"skill-catalog-version\">Arcantry {version}</p>\n  <h3>{}</h3>\n  <p class=\"skill-catalog-summary\">{}</p>\n  <p class=\"skill-catalog-command\"><code>{}</code></p>\n</a>",
        entry.name,
        escape_html(&agent.display_name),
        escape_html(&metadata.summary),
        escape_html(&entry.name)
      ),
    );
    let content = render_skill_page(entry, &metadata, &description, &agent, &version)?;
    project(
      &details_root.join(format!("{}.md", entry.name)),
      &content,
      false,
      check,
      &mut stale,
    )?;
  }

  let catalog_sections = sections
    .iter()
    .map(|section| {
      let cards = section
        .skills
        .iter()
        .map(|entry| cards.get(&entry.name).expect("validated catalog entry"))
        .cloned()
        .collect::<Vec<_>>()
        .join("\n");
      format!(
        "## {}\n\n<div class=\"skill-catalog-grid\">\n{cards}\n</div>",
        section.title
      )
    })
    .collect::<Vec<_>>()
    .join("\n\n");

  let sidebar = sections
    .iter()
    .map(|section| {
      json!({
        "label": section.title,
        "collapsed": true,
        "items": section.skills.iter().map(|entry| json!({
          "label": display_names.get(&entry.name).expect("validated skill agent"),
          "slug": format!("skills/{}", entry.name),
        })).collect::<Vec<_>>(),
      })
    })
    .collect::<Vec<_>>();
  project(
    &generated_source_root.join("skill-sidebar.ts"),
    &format!(
      "// {GENERATED_NOTICE}\nexport default {};\n",
      serde_json::to_string_pretty(&sidebar)?
    ),
    false,
    check,
    &mut stale,
  )?;
  project(
    &details_root.join("catalog.md"),
    &format!(
      "---\ntitle: Skill catalog\ndescription: Choose a focused Arcantry skill for the work at hand.\n---\n\n<!-- {GENERATED_NOTICE} -->\n\n<p class=\"skill-catalog-lead\">Choose the job. Each page explains the outcome, compatibility, and link command.</p>\n\n{catalog_sections}\n"
    ),
    false,
    check,
    &mut stale,
  )?;

  if stale && check {
    bail!("Generated tracked projections are stale. Run `just generate`.");
  }
  if !check {
    println!("Generated Arcantry projections.");
  }
  Ok(())
}

fn project_plugins(root: &Path, version: &str, check: bool, stale: &mut bool) -> Result<()> {
  let plugin = json!({
    "name": "arcantry",
    "version": version,
    "description": "Local-first project knowledge and focused agent skills.",
    "author": { "name": "Maxie", "url": "https://github.com/MrMaxie" },
    "homepage": "https://arcantry.dev/",
    "repository": "https://github.com/MrMaxie/arcantry",
    "license": "Apache-2.0",
    "keywords": ["agent-skills", "codex", "repository-lifecycle"],
    "skills": "./skills/",
    "interface": {
      "displayName": "Arcantry",
      "shortDescription": "Intent-led repositories and focused agent skills",
      "longDescription": "Coordinate project knowledge and install focused skills for self-improvement, repository safety, and content safety.",
      "developerName": "Maxie",
      "category": "Developer Tools",
      "capabilities": ["Skills", "Read", "Write"],
      "websiteURL": "https://arcantry.dev/",
      "brandColor": "#FB255F",
      "defaultPrompt": ["Use Arcantry to adopt this repository or choose the smallest focused skill for the task."]
    }
  });
  project(
    &root.join(".codex-plugin/plugin.json"),
    &format!("{}\n", serde_json::to_string_pretty(&plugin)?),
    true,
    check,
    stale,
  )?;
  let claude = json!({
    "name": "arcantry",
    "version": version,
    "description": "Local-first project knowledge and focused agent skills.",
    "author": { "name": "Maxie", "url": "https://github.com/MrMaxie" },
    "homepage": "https://arcantry.dev/",
    "repository": "https://github.com/MrMaxie/arcantry",
    "license": "Apache-2.0",
    "keywords": ["agent-skills", "claude-code", "repository-lifecycle"]
  });
  project(
    &root.join(".claude-plugin/plugin.json"),
    &format!("{}\n", serde_json::to_string_pretty(&claude)?),
    true,
    check,
    stale,
  )
}

fn render_skill_page(
  entry: &catalog::CatalogEntry,
  metadata: &catalog::SkillMetadata,
  description: &str,
  agent: &catalog::SkillAgent,
  version: &str,
) -> Result<String> {
  let scenarios = metadata
    .scenarios
    .iter()
    .map(|scenario| {
      format!(
        "### {}\n\n**Prompt**\n\n> {}\n\n**Expected outcome**\n\n{}",
        scenario.title, scenario.prompt, scenario.outcome
      )
    })
    .collect::<Vec<_>>()
    .join("\n\n");
  let compatibility = metadata
    .compatibility
    .as_ref()
    .map_or_else(String::new, |value| {
      let kinds = value
        .source_kinds
        .iter()
        .map(|kind| format!("`{kind}`"))
        .collect::<Vec<_>>()
        .join(", ");
      let adapters = value
        .adapters
        .as_ref()
        .map_or_else(String::new, |adapters| {
          format!(
            "\n\nAdapters:\n\n{}",
            adapters
              .iter()
              .map(|adapter| format!("- `{}`: `{}`", adapter.name, adapter.versions))
              .collect::<Vec<_>>()
              .join("\n")
          )
        });
      format!("## Compatibility\n\nSource kinds: {kinds}.{adapters}\n\n")
    });
  let learning = metadata
    .learning
    .as_ref()
    .map_or_else(String::new, |value| {
      format!(
        "## Learning outcomes\n\n{}\n\n",
        value
          .outcomes
          .iter()
          .map(|outcome| format!("- {outcome}"))
          .collect::<Vec<_>>()
          .join("\n")
      )
    });
  let summary = serde_json::to_string(&metadata.summary)?;
  Ok(format!(
    "---\ntitle: {}\ndescription: {summary}\n---\n\n<!-- {GENERATED_NOTICE} -->\n\n<p class=\"skill-reference-meta\"><span>Arcantry {version}</span><code>{}</code></p>\n\n{}\n\n## When to use\n\n{description}\n\n## Link this skill\n\n```sh\narcantry skills link {} --scope user\n```\n\nThe standard destination is `~/.agents/skills`. Codex reads this universal Agent Skills location directly.\n\n### Claude compatibility\n\n```sh\narcantry skills link {} --scope user --compat claude\n```\n\nThis keeps the universal link and adds a Claude alias to the same canonical package.\n\n{compatibility}{learning}## Examples\n\n{scenarios}\n",
    agent.display_name, entry.name, metadata.summary, entry.name, entry.name
  ))
}

fn escape_html(value: &str) -> String {
  value
    .replace('&', "&amp;")
    .replace('<', "&lt;")
    .replace('>', "&gt;")
    .replace('"', "&quot;")
    .replace('\'', "&#39;")
}

fn project(path: &Path, content: &str, tracked: bool, check: bool, stale: &mut bool) -> Result<()> {
  let current = if path.exists() {
    Some(fs::read_to_string(path)?)
  } else {
    None
  };
  if current.as_deref() == Some(content) {
    return Ok(());
  }
  if tracked {
    *stale = true;
  }
  if !check {
    fs::create_dir_all(path.parent().context("Generated path has no parent.")?)?;
    fs::write(path, content)?;
  }
  Ok(())
}

fn remove_generated(path: &PathBuf) -> Result<()> {
  if path.exists() {
    fs::remove_dir_all(path)?;
  }
  Ok(())
}
