use anyhow::{Context, Result, bail};
use arcantry_core::catalog;
use serde_json::json;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_NOTICE: &str = "Generated by xtask. Do not edit directly.";

struct Section<'a> {
  title: &'a str,
  skills: Vec<&'a catalog::CatalogEntry>,
}

#[derive(Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
struct SkillHistoryEntry {
  change: String,
  date: String,
  title: String,
  summary: String,
}

pub fn run(root: &Path, check: bool, docs_only: bool) -> Result<()> {
  let root = root
    .canonicalize()
    .with_context(|| format!("Could not resolve generation root {}.", root.display()))?;
  let generated_docs_root = root.join("apps/docs/src/content/docs/_generated");
  let details_root = generated_docs_root.join("skills");
  let generated_source_root = root.join("apps/docs/src/generated");
  let generated_public_root = root.join("apps/docs/public/schemas");

  if !check {
    remove_generated(&generated_docs_root)?;
    remove_generated(&generated_source_root)?;
    remove_generated(&generated_public_root)?;
  }

  let mut stale = false;
  project(
    &generated_public_root.join("arcantry-config-v1.tosd"),
    &fs::read_to_string(root.join("schemas/arcantry-config-v1.tosd"))?,
    false,
    check,
    &mut stale,
  )?;

  let (valid, errors, catalog) = catalog::validate(&root);
  if !valid {
    bail!("{}", errors.join("\n"));
  }
  let catalog = catalog.context("Catalog validation returned no catalog.")?;
  let version = arcantry_core::release::latest_standard_release_version(&root)?;
  let histories = skill_histories(&root)?;
  let manifests = catalog
    .skills
    .iter()
    .map(|entry| {
      Ok((
        entry.name.clone(),
        catalog::package_manifest(&root, &entry.name)?,
        histories.get(&entry.name).cloned().unwrap_or_default(),
      ))
    })
    .collect::<Result<Vec<_>>>()?;
  let manifest_document = manifests
    .iter()
    .map(|(name, manifest, history)| {
      json!({
        "name": name,
        "version": manifest.version,
        "role": manifest.role,
        "digest": manifest.digest,
        "files": manifest.files,
        "history": history,
      })
    })
    .collect::<Vec<_>>();
  project(
    &root.join("contracts/skill-manifests.json"),
    &format!("{}\n", serde_json::to_string_pretty(&manifest_document)?),
    true,
    check,
    &mut stale,
  )?;

  if !docs_only {
    project_plugins(&root, &version, check, &mut stale)?;
  }

  let sections = [
    ("self-improvement", "Self improvement"),
    ("repo-safely", "Repo safely"),
    ("content-safely", "Content safely"),
    ("code-quality", "Code quality"),
  ]
  .into_iter()
  .map(|(family, title)| Section {
    title,
    skills: catalog
      .skills
      .iter()
      .filter(|entry| entry.family == family)
      .collect(),
  })
  .collect::<Vec<_>>();

  let mut cards = BTreeMap::new();
  let mut display_names = BTreeMap::new();
  for entry in &catalog.skills {
    let metadata = catalog::load_skill_metadata(&root, &entry.name)?;
    let (_, description) = catalog::load_skill_frontmatter(&root, &entry.name)?;
    let agent = catalog::load_skill_agent(&root, &entry.name)?;
    display_names.insert(entry.name.clone(), agent.display_name.clone());
    cards.insert(
      entry.name.clone(),
      format!(
        "<a class=\"skill-catalog-card\" href=\"/skills/{}/\">\n  <p class=\"skill-catalog-version\">Skill {} · {}</p>\n  <h3>{}</h3>\n  <p class=\"skill-catalog-summary\">{}</p>\n  <p class=\"skill-catalog-command\"><code>{}</code></p>\n</a>",
        entry.name,
        escape_html(&metadata.version),
        escape_html(&metadata.role),
        escape_html(&agent.display_name),
        escape_html(&metadata.summary),
        escape_html(&entry.name)
      ),
    );
    let content = render_skill_page(
      entry,
      &metadata,
      &description,
      &agent,
      histories
        .get(&entry.name)
        .map(Vec::as_slice)
        .unwrap_or_default(),
    )?;
    project(
      &details_root.join(format!("{}.md", entry.name)),
      &content,
      false,
      check,
      &mut stale,
    )?;
  }

  let catalog_sections = sections
    .iter()
    .map(|section| {
      let cards = section
        .skills
        .iter()
        .map(|entry| cards.get(&entry.name).expect("validated catalog entry"))
        .cloned()
        .collect::<Vec<_>>()
        .join("\n");
      format!(
        "## {}\n\n<div class=\"skill-catalog-grid\">\n{cards}\n</div>",
        section.title
      )
    })
    .collect::<Vec<_>>()
    .join("\n\n");

  let sidebar = sections
    .iter()
    .map(|section| {
      json!({
        "label": section.title,
        "collapsed": true,
        "items": section.skills.iter().map(|entry| json!({
          "label": display_names.get(&entry.name).expect("validated skill agent"),
          "slug": format!("skills/{}", entry.name),
        })).collect::<Vec<_>>(),
      })
    })
    .collect::<Vec<_>>();
  project(
    &generated_source_root.join("skill-sidebar.ts"),
    &format!(
      "// {GENERATED_NOTICE}\nexport default {};\n",
      serde_json::to_string_pretty(&sidebar)?
    ),
    false,
    check,
    &mut stale,
  )?;
  project(
    &details_root.join("catalog.md"),
    &format!(
      "---\ntitle: Skill catalog\ndescription: Choose a focused Arcantry skill for the work at hand.\n---\n\n<!-- {GENERATED_NOTICE} -->\n\n<p class=\"skill-catalog-lead\">Choose the job. Each page explains the outcome, compatibility, and individual installation command.</p>\n\n{catalog_sections}\n"
    ),
    false,
    check,
    &mut stale,
  )?;

  if stale && check {
    bail!("Generated tracked projections are stale. Run `just generate`.");
  }
  if !check {
    println!("Generated Arcantry projections.");
  }
  Ok(())
}

fn project_plugins(root: &Path, version: &str, check: bool, stale: &mut bool) -> Result<()> {
  let package: serde_json::Value = serde_json::from_str(&fs::read_to_string(
    root.join("packages/arcantry/package.json"),
  )?)?;
  if package["version"].as_str() != Some(version) {
    bail!("Canonical package identity version does not match the current product version.");
  }
  let repository = package["repository"]["url"]
    .as_str()
    .context("Canonical package identity requires repository.url.")?
    .trim_end_matches(".git");
  let plugin = json!({
    "name": package["name"],
    "version": package["version"],
    "description": package["description"],
    "author": package["author"],
    "homepage": package["homepage"],
    "repository": repository,
    "license": package["license"],
    "keywords": ["agent-skills", "codex", "repository-lifecycle"],
    "skills": "./skills/",
    "interface": {
      "displayName": "Arcantry",
      "shortDescription": "Intent-led repositories and focused agent skills",
      "longDescription": "Coordinate project knowledge and install focused skills for self-improvement, repository safety, and content safety.",
      "developerName": "Maxie",
      "category": "Developer Tools",
      "capabilities": ["Skills", "Read", "Write"],
      "websiteURL": "https://arcantry.dev/",
      "brandColor": "#FB255F",
      "defaultPrompt": ["Use Arcantry to adopt this repository or choose the smallest focused skill for the task."]
    }
  });
  project(
    &root.join(".codex-plugin/plugin.json"),
    &format!("{}\n", serde_json::to_string_pretty(&plugin)?),
    true,
    check,
    stale,
  )?;
  let claude = json!({
    "name": package["name"],
    "version": package["version"],
    "description": package["description"],
    "author": package["author"],
    "homepage": package["homepage"],
    "repository": repository,
    "license": package["license"],
    "keywords": ["agent-skills", "claude-code", "repository-lifecycle"]
  });
  project(
    &root.join(".claude-plugin/plugin.json"),
    &format!("{}\n", serde_json::to_string_pretty(&claude)?),
    true,
    check,
    stale,
  )
}

fn render_skill_page(
  entry: &catalog::CatalogEntry,
  metadata: &catalog::SkillMetadata,
  description: &str,
  agent: &catalog::SkillAgent,
  history: &[SkillHistoryEntry],
) -> Result<String> {
  let scenarios = metadata
    .scenarios
    .iter()
    .map(|scenario| {
      format!(
        "### {}\n\n**Prompt**\n\n> {}\n\n**Expected outcome**\n\n{}",
        scenario.title, scenario.prompt, scenario.outcome
      )
    })
    .collect::<Vec<_>>()
    .join("\n\n");
  let compatibility = metadata
    .compatibility
    .as_ref()
    .map_or_else(String::new, |value| {
      let kinds = value
        .source_kinds
        .iter()
        .map(|kind| format!("`{kind}`"))
        .collect::<Vec<_>>()
        .join(", ");
      let adapters = value
        .adapters
        .as_ref()
        .map_or_else(String::new, |adapters| {
          format!(
            "\n\nAdapters:\n\n{}",
            adapters
              .iter()
              .map(|adapter| format!("- `{}`: `{}`", adapter.name, adapter.versions))
              .collect::<Vec<_>>()
              .join("\n")
          )
        });
      format!("## Compatibility\n\nSource kinds: {kinds}.{adapters}\n\n")
    });
  let learning = metadata
    .learning
    .as_ref()
    .map_or_else(String::new, |value| {
      format!(
        "## What it helps with\n\n{}\n\n",
        value
          .outcomes
          .iter()
          .map(|outcome| format!("- {outcome}"))
          .collect::<Vec<_>>()
          .join("\n")
      )
    });
  let summary = serde_json::to_string(&metadata.summary)?;
  let history = if history.is_empty() {
    "## History\n\nNo accepted skill-specific changes are recorded yet.\n\n".to_owned()
  } else {
    format!(
      "## History\n\n{}\n\n",
      history
        .iter()
        .map(|entry| format!("- **{}** - {}: {}", entry.date, entry.title, entry.summary))
        .collect::<Vec<_>>()
        .join("\n")
    )
  };
  Ok(format!(
    "---\ntitle: {}\ndescription: {summary}\n---\n\n<!-- {GENERATED_NOTICE} -->\n\n<p class=\"skill-reference-meta\"><span>Skill {} · {}</span><code>{}</code></p>\n\n{}\n\n**Use when:** {description}\n\n## Install only this skill\n\n```sh\narcantry skills link {} --scope user\n```\n\nThis links only `{}` to the standard user location, `~/.agents/skills`. Use `--scope repo` for one repository, or add `--compat claude` when that optional alias is needed.\n\n{compatibility}{learning}{history}## Examples\n\n{scenarios}\n",
    agent.display_name,
    metadata.version,
    metadata.role,
    entry.name,
    metadata.summary,
    entry.name,
    entry.name
  ))
}

fn escape_html(value: &str) -> String {
  value
    .replace('&', "&amp;")
    .replace('<', "&lt;")
    .replace('>', "&gt;")
    .replace('"', "&quot;")
    .replace('\'', "&#39;")
}

fn skill_histories(root: &Path) -> Result<BTreeMap<String, Vec<SkillHistoryEntry>>> {
  let mut histories: BTreeMap<String, Vec<SkillHistoryEntry>> = BTreeMap::new();
  for entry in walkdir::WalkDir::new(root.join("openspec/changes"))
    .min_depth(2)
    .max_depth(4)
    .into_iter()
    .filter_map(Result::ok)
    .filter(|entry| entry.file_type().is_file() && entry.file_name() == "release.md")
  {
    let source = fs::read_to_string(entry.path())?.replace("\r\n", "\n");
    let Some((frontmatter, body)) = source
      .strip_prefix("---\n")
      .and_then(|value| value.split_once("\n---\n"))
    else {
      continue;
    };
    let components = frontmatter
      .lines()
      .filter_map(|line| line.trim().strip_prefix("- skill:"))
      .map(str::trim)
      .collect::<Vec<_>>();
    if components.is_empty() {
      continue;
    }
    let change_dir = entry
      .path()
      .parent()
      .context("Release file has no change directory")?;
    let change = change_dir
      .file_name()
      .and_then(|value| value.to_str())
      .unwrap_or_default();
    let archived = change_dir
      .parent()
      .and_then(|parent| parent.file_name())
      .and_then(|value| value.to_str())
      == Some("archive");
    let (date, id) = if archived && change.len() > 11 {
      (change[..10].to_owned(), change[11..].to_owned())
    } else {
      ("Unreleased".to_owned(), change.to_owned())
    };
    let title = body
      .lines()
      .find_map(|line| line.strip_prefix("# "))
      .unwrap_or(&id)
      .trim()
      .to_owned();
    let summary = body
      .lines()
      .skip_while(|line| !line.starts_with("# "))
      .skip(1)
      .find(|line| !line.trim().is_empty())
      .unwrap_or_default()
      .trim()
      .to_owned();
    for name in components {
      histories
        .entry(name.to_owned())
        .or_default()
        .push(SkillHistoryEntry {
          change: id.clone(),
          date: date.clone(),
          title: title.clone(),
          summary: summary.clone(),
        });
    }
  }
  for history in histories.values_mut() {
    history.sort_by(|left, right| {
      right
        .date
        .cmp(&left.date)
        .then(left.change.cmp(&right.change))
    });
  }
  Ok(histories)
}

fn project(path: &Path, content: &str, tracked: bool, check: bool, stale: &mut bool) -> Result<()> {
  let current = if path.exists() {
    Some(fs::read_to_string(path)?)
  } else {
    None
  };
  if current.as_deref() == Some(content) {
    return Ok(());
  }
  if tracked {
    *stale = true;
  }
  if !check {
    fs::create_dir_all(path.parent().context("Generated path has no parent.")?)?;
    fs::write(path, content)?;
  }
  Ok(())
}

fn remove_generated(path: &PathBuf) -> Result<()> {
  if path.exists() {
    fs::remove_dir_all(path)?;
  }
  Ok(())
}
